window.API_ATLAS_CATALOG = {
  meta: {
    name: "API Atlas — Finance Edition",
    version: "0.1.0",
    source: "public-apis/public-apis",
    sourceLicense: "MIT",
    sourceSnapshot: "2026-07-13",
    disclaimer: "الإدراج يعني أن الخدمة كانت موجودة في دليل public-apis عند إعداد النسخة، ولا يعني أنها اختُبرت أو اعتُمدت تشغيليًا."
  },
  items: [
    {
      id: "alpha-vantage",
      name: "Alpha Vantage",
      description: "بيانات أسهم تاريخية ولحظية نسبيًا، مؤشرات فنية وبيانات اقتصادية.",
      auth: "apiKey",
      https: true,
      cors: "Unknown",
      freeTier: true,
      type: "Market Data",
      docs: "https://www.alphavantage.co/documentation/",
      tags: ["أسهم", "مؤشرات فنية", "فوركس", "كريبتو"],
      notes: "الخطة المجانية محدودة الطلبات؛ يلزم اختبار التأخير والتغطية لكل استخدام."
    },
    {
      id: "alpaca",
      name: "Alpaca Market Data",
      description: "بيانات سوق أمريكي تاريخية ولحظية وواجهات WebSocket ضمن منظومة Alpaca.",
      auth: "apiKey",
      https: true,
      cors: "Unknown",
      freeTier: true,
      type: "Market Data",
      docs: "https://docs.alpaca.markets/docs/about-market-data-api",
      tags: ["أسهم أمريكية", "WebSocket", "تاريخي"],
      notes: "التغطية اللحظية تختلف باختلاف الخطة ومصدر تغذية السوق."
    },
    {
      id: "financial-modeling-prep",
      name: "Financial Modeling Prep",
      description: "أسعار، قوائم مالية، نسب، أخبار وبيانات أساسية للشركات.",
      auth: "apiKey",
      https: true,
      cors: "Unknown",
      freeTier: true,
      type: "Fundamentals",
      docs: "https://site.financialmodelingprep.com/developer/docs",
      tags: ["قوائم مالية", "نسب", "أسعار", "أخبار"],
      notes: "يجب مراجعة حدود الخطة وحقوق إعادة عرض البيانات قبل الاستخدام التجاري."
    },
    {
      id: "finnhub",
      name: "Finnhub",
      description: "بيانات أسهم وفوركس وكريبتو وأخبار وبيانات شركات عبر REST وWebSocket.",
      auth: "apiKey",
      https: true,
      cors: "Unknown",
      freeTier: true,
      type: "Market Data",
      docs: "https://finnhub.io/docs/api",
      tags: ["أسهم", "أخبار", "WebSocket", "مشاعر"],
      notes: "بعض البيانات المتقدمة أو اللحظية قد تتطلب خطة مدفوعة."
    },
    {
      id: "fred",
      name: "FRED",
      description: "سلاسل اقتصادية كلية من بنك الاحتياطي الفيدرالي في سانت لويس.",
      auth: "apiKey",
      https: true,
      cors: "Unknown",
      freeTier: true,
      type: "Macroeconomics",
      docs: "https://fred.stlouisfed.org/docs/api/fred/",
      tags: ["اقتصاد كلي", "فوائد", "تضخم", "وظائف"],
      notes: "مصدر رسمي ممتاز للاقتصاد الكلي، وليس مصدر أسعار أسهم لحظية."
    },
    {
      id: "marketstack",
      name: "Marketstack",
      description: "واجهة لبيانات سوق عالمية تاريخية وداخل الجلسة بحسب الخطة.",
      auth: "apiKey",
      https: true,
      cors: "Unknown",
      freeTier: true,
      type: "Market Data",
      docs: "https://marketstack.com/documentation",
      tags: ["أسواق عالمية", "تاريخي", "Intraday"],
      notes: "تحقق من عمر البيانات وحدود HTTPS والخطة المجانية قبل الاعتماد."
    },
    {
      id: "nasdaq-data-link",
      name: "Nasdaq Data Link",
      description: "مجموعات بيانات مالية واقتصادية من مزودين متعددين.",
      auth: "apiKey",
      https: true,
      cors: "Unknown",
      freeTier: true,
      type: "Data Marketplace",
      docs: "https://docs.data.nasdaq.com/",
      tags: ["Datasets", "اقتصاد", "أسواق"],
      notes: "بعض المجموعات مجانية وبعضها مدفوع؛ كل Dataset له شروطه الخاصة."
    },
    {
      id: "openfigi",
      name: "OpenFIGI",
      description: "تحويل وتوحيد رموز الأدوات المالية باستخدام معرفات FIGI.",
      auth: "apiKey",
      https: true,
      cors: "Unknown",
      freeTier: true,
      type: "Symbology",
      docs: "https://www.openfigi.com/api",
      tags: ["رموز", "FIGI", "توحيد الأدوات"],
      notes: "مفيد لتطابق الرموز بين المزودين، وليس مصدر أسعار."
    },
    {
      id: "polygon",
      name: "Polygon",
      description: "بيانات أسهم وخيارات وفوركس وكريبتو تاريخية ولحظية بحسب الخطة.",
      auth: "apiKey",
      https: true,
      cors: "Unknown",
      freeTier: true,
      type: "Market Data",
      docs: "https://polygon.io/docs",
      tags: ["أسهم", "خيارات", "WebSocket", "Ticks"],
      notes: "التغطية الكاملة والبيانات اللحظية عادة مرتبطة بنوع الاشتراك."
    },
    {
      id: "portfolio-optimizer",
      name: "Portfolio Optimizer",
      description: "تحليل وتحسين المحافظ وإحصاءات المخاطر والعائد.",
      auth: "No",
      https: true,
      cors: "Yes",
      freeTier: true,
      type: "Portfolio Analytics",
      docs: "https://portfoliooptimizer.io/",
      tags: ["محافظ", "تحسين", "مخاطر"],
      notes: "اختبر حدود الاستخدام وصحة المنهجية قبل أي قرار مالي."
    },
    {
      id: "sec-edgar",
      name: "SEC EDGAR Data",
      description: "إفصاحات وملفات الشركات الأمريكية من هيئة الأوراق المالية والبورصات.",
      auth: "No",
      https: true,
      cors: "Unknown",
      freeTier: true,
      type: "Regulatory Filings",
      docs: "https://www.sec.gov/edgar/sec-api-documentation",
      tags: ["SEC", "10-K", "10-Q", "8-K"],
      notes: "مصدر رسمي؛ يجب الالتزام بسياسة User-Agent وحدود الطلبات لدى SEC."
    },
    {
      id: "stockdata",
      name: "StockData",
      description: "أسعار تاريخية وداخل الجلسة وأخبار ومشاعر السوق.",
      auth: "apiKey",
      https: true,
      cors: "Unknown",
      freeTier: true,
      type: "Market Data",
      docs: "https://www.stockdata.org/documentation",
      tags: ["أسعار", "أخبار", "مشاعر"],
      notes: "تحقق من التغطية الفعلية للأسهم الصغيرة ومن التأخير في الخطة المجانية."
    },
    {
      id: "tradier",
      name: "Tradier",
      description: "بيانات أسهم وخيارات أمريكية وواجهات مرتبطة بحسابات الوساطة.",
      auth: "OAuth",
      https: true,
      cors: "Unknown",
      freeTier: true,
      type: "Broker & Market Data",
      docs: "https://documentation.tradier.com/",
      tags: ["أسهم", "خيارات", "وساطة"],
      notes: "البيانات والوظائف المتاحة تختلف بين بيئة الاختبار والحساب الفعلي."
    },
    {
      id: "twelve-data",
      name: "Twelve Data",
      description: "أسهم وفوركس وكريبتو ومؤشرات فنية عبر REST وWebSocket.",
      auth: "apiKey",
      https: true,
      cors: "Unknown",
      freeTier: true,
      type: "Market Data",
      docs: "https://twelvedata.com/docs",
      tags: ["أسهم", "فوركس", "مؤشرات", "WebSocket"],
      notes: "راجع Credits المطلوبة لكل Endpoint وحدود الخطة المجانية."
    },
    {
      id: "econdb",
      name: "Econdb",
      description: "بيانات اقتصادية كلية عالمية عبر واجهة بسيطة.",
      auth: "No",
      https: true,
      cors: "Unknown",
      freeTier: true,
      type: "Macroeconomics",
      docs: "https://www.econdb.com/api/",
      tags: ["اقتصاد عالمي", "GDP", "تضخم"],
      notes: "مفيد للمؤشرات الاقتصادية؛ تحقق من تكرار التحديث ومصدر كل سلسلة."
    },
    {
      id: "congress-invests",
      name: "CongressInvests",
      description: "بيانات إفصاحات تداول أعضاء الكونغرس الأمريكي.",
      auth: "No",
      https: true,
      cors: "Unknown",
      freeTier: true,
      type: "Alternative Data",
      docs: "https://www.congressinvests.com/",
      tags: ["كونغرس", "تداولات داخلية", "بيانات بديلة"],
      notes: "الإفصاحات قد تكون متأخرة زمنيًا ولا تمثل توصيات استثمارية."
    }
  ]
};
